#****************************************************************************************
# ██╗   ██╗██╗██████╗ ████████╗██╗   ██╗ █████╗ ██╗     ███████╗██╗  ██╗ ██████╗ ██████╗ 
# ██║   ██║██║██╔══██╗╚══██╔══╝██║   ██║██╔══██╗██║     ██╔════╝██║  ██║██╔═══██╗██╔══██╗
# ██║   ██║██║██████╔╝   ██║   ██║   ██║███████║██║     ███████╗███████║██║   ██║██████╔╝
# ╚██╗ ██╔╝██║██╔══██╗   ██║   ██║   ██║██╔══██║██║     ╚════██║██╔══██║██║   ██║██╔═══╝ 
#  ╚████╔╝ ██║██║  ██║   ██║   ╚██████╔╝██║  ██║███████╗███████║██║  ██║╚██████╔╝██║     
#   ╚═══╝  ╚═╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚═╝     
#   *******************************************************************************
# Programmed by Pikod, please subscribe my channel and join my discord for new updates.
# https://www.youtube.com/c/pikod - https://discord.gg/dkbNmFJ - pikod@shark-mc.com

# Categories Menu Size (1-6)
categoryMenuSize: 3

# MENU / CHAT
shoppingType: MENU