name: VirtualShop
version: 1.0.5
descreption: Virtual Shop plugin (English Language).
author: HzPikod
softdepend: [Vault]
main: me.pikod.main.VirtualShop
api-version: 1.15
website: https://wwww.youtube.com/pikod
commands:
    virtualshop:
        descreption: Opens admin panel
        aliases: [vs]
        usage: /vs
    shop:
        descreption: Opens shop
        aliases: [shop, market]
        usage: /shop
permissions:
    virtualshop.manage:
        descreption: Admin panel permission.
    virtualShop.shop:
        descreption: Shop open permission.
        default: true