name: VirtualShop
version: 1.0.3
descreption: Virtual Shop plugin (English Language).
author: HzPikod
softdepend: [Vault]
main: me.pikod.main.VirtualShop
website: https://wwww.youtube.com/pikod
commands:
    virtualshop:
        descreption: Opens admin panel
        aliases: [vs]
        usage: /vs
    market:
        descreption: Opens shop
        aliases: [shop]
        usage: /market
permissions:
    virtualshop.manage:
        descreption: Admin panel permission.
    virtualShop.shop:
        descreption: Shop open permission.
        default: true