name: VirtualShop
version: 1.0.7
description: Virtual Shop plugin (with Admin GUI)
author: HzPikod
softdepend: [Vault]
main: me.pikod.main.VirtualShop
api-version: 1.15
website: https://wwww.youtube.com/pikod
commands:
    virtualshop:
        description: Opens admin panel
        aliases: [vs]
        usage: /vs
    shop:
        description: Opens shop
        aliases: [shop, market]
        usage: /shop
    sell:
        description: Sell item
        aliases: [sat]
        usage: "/sell all hand"
permissions:
    virtualshop.manage:
        description: Admin panel permission.
    virtualShop.shop:
        description: Shop open permission.
        default: true
    virtualshop.sell:
        description: Sell hand/all command permission.
        default: true