name: VirtualShop
version: 1.0.3
descreption: Sanal market plugini (Türkçe Düzenleme)
author: HzPikod
softdepend: [Vault]
main: me.pikod.main.VirtualShop
website: https://wwww.youtube.com/pikod
commands:
    virtualshop:
        descreption: Yönetim Panelini açar
        aliases: [vs]
        usage: /vs
    market:
        descreption: Marketi açar
        aliases: [shop]
        usage: /market
permissions:
    virtualshop.manage:
        descreption: Admin menü açma yetkisi.
    virtualShop.shop:
        descreption: Market menüsünü açma yetkisi
        default: true